NumPy (*numerical python*) is a useful library optimized for numerical operations

In [5]:
import numpy as np

Creating a simple array.

In [6]:
x = np.array([1,2,3,4], dtype=np.uint32)
print(x)

[1 2 3 4]


An array of zeros

In [18]:
np.zeros(10, dtype=np.uint8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [19]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.full((3,5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.random.random((3,3))

array([[0.76891373, 0.02246956, 0.02655507],
       [0.83487696, 0.91054031, 0.18162034],
       [0.66008232, 0.74567292, 0.75326538]])

Create a 3x3 matrix of normally distributed values with mean of 0 and standard deviation of 0.

In [25]:
np.random.normal(0, 1, (3,3))

array([[-1.89141094,  0.94449073,  0.62421335],
       [ 1.86218393,  0.60833553,  1.39591501],
       [ 0.30724954,  0.78404346,  0.0584529 ]])

In [26]:
np.random.randint(0, 20, (3,5))

array([[ 5,  5, 19, 14, 15],
       [ 0,  0,  6,  9, 12],
       [10, 19,  4, 12,  7]])

In [27]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.empty((3,3))

array([[1.89141094, 0.94449073, 0.62421335],
       [1.86218393, 0.60833553, 1.39591501],
       [0.30724954, 0.78404346, 0.0584529 ]])

Notice how np.empty((m,n)) takes random values in memory and places them into the matrix.