In [186]:
import numpy as np
import time

In [187]:
np.random.seed(0) #is a starting number used to generate subsequent random numbers

In [188]:
x1 = np.random.randint(10, size=6)

In [189]:
x2 = np.random.randint(10, size=(3,4))

In [190]:
x3 = np.random.randint(10, size=(3,4,5))

In [191]:
print(f'The dimension is {x1.ndim}')

The dimension is 1


In [192]:
print(f'The shape is {x1.shape}')

The shape is (6,)


In [193]:
print(f'The size is {x1.size}')

The size is 6


The shape tells us how many elements we have in each dimension.

In [194]:
print(f'The dimension is {x2.ndim}')

The dimension is 2


In [195]:
print(f'The shape is {x2.shape}')

The shape is (3, 4)


So 3 rows and 4 columns

In [196]:
print(f'The size is {x2.size}')

The size is 12


So bascially 3x4 a.k.a total number of elements

In [197]:
print(x1)
x1[1]

[5 0 3 3 7 9]


0

In [198]:
print(x2)
x2[0,0]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


3

In [199]:
x2[0,-1]

4

In [200]:
x2[0,0] = 99 #modifying a given element

In [201]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [202]:
x2[0,0] = 3.14

In [203]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Real part of 3.14 is truncated. We only get integer part. **If you create an integer array and add a float, the float is truncated to integer part.**

In [204]:
print(x1)
print(x1[1:4]) #Slicing
print(x1[1:5:2]) #Slicing with step

[5 0 3 3 7 9]
[0 3 3]
[0 3]


In [205]:
print(x1[::-1])

[9 7 3 3 0 5]


## Multidimensional Arrays

In [206]:
print(x2)
print(x2[:2,:3]) #first 2 rows and first 3 columns

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]


Extracting rows/columns

In [207]:
print(x2[:,0])

[3 7 1]


In [208]:
print(x2[1,:]) #accessing 1st row

[7 6 8 8]


In [209]:
print(x2[1]) #optimized way to access 1st row

[7 6 8 8]


Extracting submatrices

In [210]:
x2_sub = x2[:2, :2]

In [211]:
print(x2)
print(x2_sub)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]


In [212]:
x2_sub[0,0] = 99

In [213]:
print(x2)
print(x2_sub)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]


**NOTICE** Something strange happened! The original x2 matrix was also modified. 
How to create a copy that does not change the original array?

In [214]:
x2 = np.random.randint(10, size=(3,4))

In [215]:
x2_copy = x2[:2,:2].copy()
x2_copy[0,0] = 99

In [216]:
print(x2)
print(x2_copy)

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]
[[99  3]
 [ 8  4]]


## Splitting and merging arrays together

In [217]:
x1 = np.random.randint(10, size=9)

In [218]:
x2 = np.random.randint(10, size=(3,4))

In [219]:
x3 = np.random.randint(10, size=(3,4,5))

In [220]:
x1_grid = x1.reshape((3,3))

In [221]:
print(x1)
print(x1_grid)

[5 9 3 0 5 0 1 2 4]
[[5 9 3]
 [0 5 0]
 [1 2 4]]


What if the size is not known?

In [222]:
x1_grid = x1.reshape((3,-1)) #-1 is a jolly value, meaning that i specified that I want 3 rows and if you find -1 you have to compute yourself how many dimensions

In [223]:
print(x1_grid)

[[5 9 3]
 [0 5 0]
 [1 2 4]]


In [224]:
x1_grid = x1.reshape((-1,3))

#### Going from a matrix to an array

In [225]:
x2_linear = x2.reshape((1,-1)) # BUT reshape(-1) doesn't make a matrix of one row, but just one array

In [226]:
print(x2)
print(x2_linear)

[[2 0 3 2]
 [0 7 5 9]
 [0 2 7 2]]
[[2 0 3 2 0 7 5 9 0 2 7 2]]


### How to concatenate and split arrays

In [227]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [228]:
new_array = np.concatenate([x,y])
print(new_array)

[1 2 3 4 5 6]


In [229]:
z = np.array([[1,2,3],
              [4,5,6]])
print(z)

[[1 2 3]
 [4 5 6]]


In [230]:
new_array = np.concatenate([z,z])
print(new_array)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [231]:
x = np.array([7,8,9])
y = np.array([[99], [99]])

In [232]:
new_array = np.vstack([z,x])
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [233]:
new_array = np.hstack([z,y])
print(new_array)

[[ 1  2  3 99]
 [ 4  5  6 99]]


##### Splitting arrays

In [234]:
x =  np.array([1,2,3,4,5,6,7,8,9])

In [235]:
x_slice = np.split(x,[3])
print(x_slice)

[array([1, 2, 3]), array([4, 5, 6, 7, 8, 9])]


In [236]:
x1, x2, x3 = np.split(x,[3,6])
print(x1)
print(x2)
print(x3)

[1 2 3]
[4 5 6]
[7 8 9]


In [237]:
z = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [238]:
x1, x2 = np.vsplit(z,[1]) #vertically splitting the array
print(x1)
print(x2)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]


In [239]:
x1, x2 = np.hsplit(z,[1])
print(z)
print(x1)
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
[[2 3]
 [5 6]
 [8 9]]
